"""Initial schema

Revision ID: 2a84f7f1ae34
Revises: 
Create Date: 2024-05-21 21:42:12.023059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import shroudstone.db.schema


# revision identifiers, used by Alembic.
revision: str = "2a84f7f1ae34"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("nickname_discriminator", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "renamehistory",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("renamed_at", sa.DateTime(), nullable=False),
        sa.Column(
            "old_path", shroudstone.db.schema.PathString(), nullable=False
        ),
        sa.Column(
            "new_path", shroudstone.db.schema.PathString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "replayfile",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("md5sum", sa.String(), nullable=False),
        sa.Column("path", shroudstone.db.schema.PathString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("build_number", sa.Integer(), nullable=False),
        sa.Column("map_name", sa.String(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("is_1v1_ladder_game", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_replayfile_md5sum"), "replayfile", ["md5sum"], unique=False
    )
    op.create_table(
        "playerslot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("replay_id", sa.Integer(), nullable=False),
        sa.Column("player_uuid", sa.Uuid(), nullable=True),
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("nickname_discriminator", sa.String(), nullable=True),
        sa.Column("is_spectator", sa.Boolean(), nullable=False),
        sa.Column("faction", sa.String(), nullable=True),
        sa.Column("is_ai", sa.Boolean(), nullable=False),
        sa.Column("disconnect_time", sa.Float(), nullable=True),
        sa.Column("leave_reason", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_uuid"],
            ["player.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["replay_id"],
            ["replayfile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playerslot")
    op.drop_index(op.f("ix_replayfile_md5sum"), table_name="replayfile")
    op.drop_table("replayfile")
    op.drop_table("renamehistory")
    op.drop_table("player")
    # ### end Alembic commands ###
