# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Aggregation(str, Enum):
    """
    Aggregation
    """

    """
    allowed enum values
    """
    LAST = 'last'
    MAX_MMR = 'max_mmr'
    MAX_POINTS = 'max_points'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Aggregation from a JSON string"""
        return cls(json.loads(json_str))


