# coding: utf-8

"""
    api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class League(str, Enum):
    """
    League
    """

    """
    allowed enum values
    """
    ASPIRANT = 'aspirant'
    BRONZE = 'bronze'
    SILVER = 'silver'
    GOLD = 'gold'
    PLATINUM = 'platinum'
    DIAMOND = 'diamond'
    MASTER = 'master'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of League from a JSON string"""
        return cls(json.loads(json_str))


